# Generated by Django 4.2.15 on 2024-08-18 06:13

import blog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "gif"]
                            ),
                            blog.validators.validate_image_size,
                        ],
                    ),
                ),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("blog", "Blog Post"), ("review", "Review Post")],
                        default="blog",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
